name: Python package

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests beautifulsoup4
        
    - name: Set up Environment Variables
      run: |
        echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
    - name: Run Python script
      run: |
        python main.py
